# Environment name which should equal to Git branch name
master:

  # SSH user to be used in deployment
  user: TnyaM

  # Server hostname or IP address for deployment
  hostname: 34.222.243.76 
    
  deploy_path: ~/app
