# This is a basic workflow to help you get started with Actions

name: Deploying WordPress Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: files.000webhost.com
        port: 21
        password: ${{ secrets.WORDPRESS_PASSWORD }}
        username: ${{ secrets.WORDPRESS_USERNAME }}
        local-dir: ./app/public/
        server-dir: ./app/public/
